name: eggybyte_core
description: "A foundational Flutter package providing essential utilities and core functionalities for EggyByte Technology applications with automatic platform detection and smart logging."
version: 1.1.1
homepage: https://github.com/eggybyte-technology/flutter-eggybyte-core
repository: https://github.com/eggybyte-technology/flutter-eggybyte-core
issue_tracker: https://github.com/eggybyte-technology/flutter-eggybyte-core/issues
documentation: https://pub.dev/documentation/eggybyte_core/latest/

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  path_provider: ^2.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - utilities
  - logging
  - networking
  - formatting
  - storage
  - platform-detection
  - core-library

funding:
  - https://github.com/sponsors/eggybyte-technology

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
