name: eggybyte_core
description: "A foundational Flutter package providing essential utilities and core functionalities for EggyByte Technology applications with automatic platform detection and smart logging."
version: 1.0.4
homepage: https://github.com/eggybyte-technology/flutter-eggybyte-core
repository: https://github.com/eggybyte-technology/flutter-eggybyte-core
issue_tracker: https://github.com/eggybyte-technology/flutter-eggybyte-core/issues
documentation: https://pub.dev/documentation/eggybyte_core/latest/

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0       # For NetworkUtils HTTP operations
  path_provider: ^2.1.5  # For StorageUtils file operations
  intl: ^0.20.2      # For date/time formatting in FormatUtils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# Package information
topics:
  - utilities
  - logging
  - networking
  - formatting
  - storage
  - platform-detection
  - core-library

funding:
  - https://github.com/sponsors/eggybyte-technology

# Screenshots for pub.dev (if applicable)
# screenshots:
#   - description: 'Logging utilities demo'
#     path: screenshots/logging_demo.png

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
